"""baseline schema

Revision ID: 8917b0ddbc06
Revises: 
Create Date: 2026-05-07 20:54:16.860166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8917b0ddbc06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workos_user_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('github_access_token', sa.Text(), nullable=True),
    sa.Column('gitlab_access_token', sa.Text(), nullable=True),
    sa.Column('bitbucket_access_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_workos_user_id'), 'users', ['workos_user_id'], unique=True)
    op.create_table('project_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('github_repo_url', sa.String(length=500), nullable=True),
    sa.Column('zip_file_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dependencies_count', sa.Integer(), nullable=False),
    sa.Column('updates_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_history_created_at'), 'project_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_history_session_id'), 'project_history', ['session_id'], unique=True)
    op.create_index(op.f('ix_project_history_status'), 'project_history', ['status'], unique=False)
    op.create_index(op.f('ix_project_history_user_id'), 'project_history', ['user_id'], unique=False)
    op.create_table('project_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('project_synopsis', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('github_repo_url', sa.String(length=500), nullable=True),
    sa.Column('github_owner', sa.String(length=255), nullable=True),
    sa.Column('github_repo_name', sa.String(length=255), nullable=True),
    sa.Column('github_default_branch', sa.String(length=100), nullable=True),
    sa.Column('zip_file_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('has_updatable_dependencies', sa.Boolean(), nullable=True),
    sa.Column('dependencies_count', sa.Integer(), nullable=False),
    sa.Column('outdated_dependencies_count', sa.Integer(), nullable=False),
    sa.Column('dependency_files', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_library_created_at'), 'project_library', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_library_user_id'), 'project_library', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme', sa.String(length=30), nullable=False),
    sa.Column('theme_auto_mode', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('high_contrast', sa.Boolean(), nullable=False),
    sa.Column('colorblind_mode', sa.String(length=20), nullable=True),
    sa.Column('font_size', sa.String(length=10), nullable=False),
    sa.Column('reduce_motion', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('custom_instructions', sa.Text(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('pull_request_url', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=50), nullable=True),
    sa.Column('job_config', sa.JSON(), nullable=True),
    sa.Column('job_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_library.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_session_id'), 'jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_session_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_project_library_user_id'), table_name='project_library')
    op.drop_index(op.f('ix_project_library_created_at'), table_name='project_library')
    op.drop_table('project_library')
    op.drop_index(op.f('ix_project_history_user_id'), table_name='project_history')
    op.drop_index(op.f('ix_project_history_status'), table_name='project_history')
    op.drop_index(op.f('ix_project_history_session_id'), table_name='project_history')
    op.drop_index(op.f('ix_project_history_created_at'), table_name='project_history')
    op.drop_table('project_history')
    op.drop_index(op.f('ix_users_workos_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
